name: CI
on:
  push:
    branches: [main]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Cache Dependencies
        uses: actions/cache@v6
        with:
          path: build/_deps
          key: ${{runner.os}}-${{hashFiles('CMakeLists.txt')}}
      - name: Configure and build
        env:
          CC: gcc-14
          CXX: g++-14
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build
      - name: Test
        run: ctest --test-dir build --output-on-failure
            
