name: CI
on:
  push:
    branches: [main]

jobs:
  test:
    name: Test
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Cache Dependencies
        uses: actions/cache@v6
        with:
          path: build/_deps
          key: ${{runner.os}}-${{hashFiles('CMakeLists.txt')}}
      - name: Install GCC 13
        run: |
          sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
          sudo apt update
          sudo apt install -y gcc-13 g++-13
      - name: Configure and build
        run: |
          CC=gcc-13 CXX=g++-13 cmake -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build
      - name: Test
        run: ctest --test-dir build --output-on-failure
            
